### PR TITLE
Fix routing errror where start page was given on api requests

### PR DESCRIPTION
**Pull request by nassir90**
My 'fix' to the url routing actually made all API routes return the template index html file.

This patches that behavior.

### CODE REVIEW

**Review by ni-sauvage — COMMENTED** [review]
I believe this is probably related to [PR #113](https://github.com/MaxCunningham19/legal_spellcheck/pull/113). Just to enquire, is this PR necessary after the previous one?

**Comment by nassir90** [comment]
The previous one didn't work when I was messing around with the frontend. An example of a case where it didn't work is when you try to access the `api/document` route. The problem is only the route `api/document/` is defined (with a trailing slash). Rather than stop searching for matches within the API router, django will keep on searching untill it finds the catch all rotue in the client urls.py file, and it will serve the index html page in response to a REST GET request! With this PR, the final route is not a catch all, so no valid route will be found for `api/document`. At that point django will send a 303 to the client redirecting to `api/document/`, which will work.

**Comment by nassir90** [comment]
You should encounter the bug if you navigate on `main` for long enough.

**Comment by MaxCunningham19** [comment]
What is the story with this PR? Should it be closed or is there a resolution to the above questions?

**Comment by ni-sauvage** [comment]
> What is the story with this PR? Should it be closed or is there a resolution to the above questions?

I'm not able to replicate the bug described in [this previous comment](https://github.com/MaxCunningham19/legal_spellcheck/pull/117#issuecomment-1485879499) with regards to `api/document`, so I believe it is fixed. Should we encounter errors, we can reopen the PR.

**Pull request closed without merging**
