### PR TITLE
Sprint1: REST API

### PR DESCRIPTION
**Pull request by QimingNie**

### CODE REVIEW

**Comment by nassir90** [comment]
Django was having a fit since it didn't know what 'UTC' was

**Review by MaxCunningham19 — APPROVED** [review]
LGTM

**Comment by nassir90** [comment]
You need to remove the `__pycache__` folders.

**Review by MaxCunningham19 — CHANGES_REQUESTED** [review]
I have a few questions and changes I think would be good. If there is a reason for something I ask to change just let me know why and the reasoning and we can find a solution.

What are the folders called QAQ_name? (QAQ_api,QAQ_project).

Why is the folder structure as it is currently:
```
API
  |-- QAQ_api     
  |-- QAQ_project
  |- db.sql
  |- manage.py
```
Could it not be simplified to just having the main API folder similar to the structure [here](https://github.com/techwithtim/Music-Controller-Web-App-Tutorial/tree/main/Tutorial%2017).
```
API
  |-- QAQ_api     
  |- db.sql
  |- manage.py
```

There just seems to be a lot of extra complexity in the project structure then is necessary.
Besides the Project structure and naming issues the actually code itself looks good to me, @ni-sauvage might have a different opinion/view that would be good to get.

**Comment by ni-sauvage** [comment]
I'd tend to agree with @MaxCunningham19 here, but we can clarify tomorrow during the team meeting as to the necessity of this project structure.

**Comment by nassir90** [comment]
This should be ready to go now. There will be major conflicts with my branch but I will just have to fix them.

**Review by MaxCunningham19 — APPROVED** [review]
LGTM - haven't had time to check docker containers, assuming you can run them on your own machine it seems good

**Comment by nassir90** [comment]
There are some problems with static files in this branch, as in the main branch, but these are fixed in my other PR. I've added a github workflow to ensure that all static files are loaded properly in that one.

**Pull request merged**
