### PR TITLE
Added Django WrkFlo For Testing

### PR DESCRIPTION
**Pull request by MaxCunningham19**

### CODE REVIEW

**Comment by nassir90** [comment]
Testing for the MVP will probably have to be done in docker. A command like this should work: `docker compose run --entrypoint 'bash -c ". scripts/install.sh && python3 manage.py test"' webserver-local`

**Comment by nassir90** [comment]
Also the psycopg library or whatever its called is needed to communicate with postgres.

**Comment by MaxCunningham19** [comment]
Yeah - Im thinking for this project/module we only need to do unit testing thus we can moc/fake backends/data using dependency injection ect so It might be best to stick with pytest since it works with GitHub Actions. What do you think?

**Comment by nassir90** [comment]
I guess it will be fine with pytest if we only need unit testing. We will just have to make most logic occur in framework-agnostic code (outside of django views) that can be tested without Django running at all.
#

**Comment by MaxCunningham19** [comment]
Yeah I think that framework agnostic code is best for this application as it will teach good design principals to do with coupling modularisation ect as well as making the code easier to test. Going to close this PR for the moment - in the event that we change our minds in the future we can reopen this

**Pull request closed without merging**
