### PR TITLE
Sprint 2: Browse My Documents section

### PR DESCRIPTION
**Pull request by max-romagnoli**
### Features completed
* Refactored the `MyDocuments `page and `Explorer `component to generate a new `Editor `instance on click. This allows to access each document.
* Refactored `Carousel `and `Explorer `to map and read data predicting API models for integration (tagging @ni-sauvage on this as a follow up from our conversations).
* Added inactive functions to consume API in `MyDocuments `(same @ni-sauvage)
* Switched to grid display view for PreviewIcon to avoid overflow bugs. Now titles can be also two rows long, although this might not be definitive.

### Features in-progress (I will open new issues for these)
* Something which is still in-progress and dependent on the API is the ability to _persist_ the data and then be able to save edited documents. This might involve a system change in the Backend (@ni-sauvage) team, as they would probably need to implement a second document view that contains only the saved documents: currently I believe the system is setup so that if you edit an existing document if you post the changes these will be overwritten. This is not ideal if the user is editing a piece of legislation: instead a copy of the document should be generated (for example with key: <title>+ " copy") and then accessed from `MyDocuments`.
* Router Links: it is currently not possible to navigate with the history buttons. What we should aim for is a Router system where the documents create a new router instance called mydocuments/documentname so that we are able to navigate back and forth.

### Known bugs (I will open single PRs to fix these)
* I noticed that there is a bug when deleting paragraphs in `Carousel`. On delete, the paragraph won't update the index and cause certain paragraphs to be unmapped.
* PreviewIcon is still not optimal. If the title is more than two lines it will most likely break the body preview.

#53

### CODE REVIEW

**Review by MaxCunningham19 — APPROVED** [review]
# LGTM

## Points to Note

#### Document Persistence and Saving

the user should be able to save individual blocks so that these are posted to the backend rather then the whole document. And then we don't have to deal with overwriting the whole document. If we have time at the end we can implement a persistence/ last_save feature but this can be ignored for now as its not really in the project scope. Document versioning wasn't part of the project requirements.

#### Router Links

This isn't an issue for me - I'm using google chrome on an m1 so maybe its just for certain browsers?

#### Carousel Renumbering
This is a high priority as the lack of renumbering will also cause issues on the backend -  the easiest issue would be to change how you are storing the blocks , currently you are doing the below

```
"blocks": [
                {
                    "block_content": "block text",
                    "block_order": 0
                },
                {
                    "block_content": "Bitta TEXT.",
                    "block_order": 1
                },
                {
                    "block_content": "Text.",
                    "block_order": 2
                },
                {
                    "block_content": "Other Tex.",
                    "block_order": 3
                }
            ]
```
would you not just store this in an array and then the order is done by the array? i.e the above becomes:
```
"blocks": [
               "block text",
               "Bitta TEXT.",
               "Text.",
               "Other Tex."
            ]
```
#### PreviewIcon
While its good to try work these issues out I would focus on getting connected to the backend for this sprint and maybe next sprint work on this - worst comes to worst change it to a simple list with only the document name

**Comment by max-romagnoli** [comment]
@ni-sauvage @MaxCunningham19 @ciannamacmahon 
Summing up all the considerations made on these points:

#### Document persistence and saving
Two things:
* I had a chat with Max in which he clarified the scope of the project: for now we will keep the app structured so that all the documents edited/created are in MyDocuments whereas Browse serves as the Editor.
* After a chat with Niall and Ignati I agreed to provide them with a list of use cases to develop the new views and related endpoints needed for this.
I will post this into the Backend discord channel so that you guys can review them and check all the priorities.
I will try to get this done by tomorrow, if not today.

#### Router links
I have been trying this on both Chrome and Firefox and I believe that the issue persists. 
The reason for this is that the MyDocuments.js page displays conditionally either the `Explorer.js` or the `Editor.js`. It doesn't actually change page, therefore each document does not have its own unique link. As a consequence, if one tries to use the browser back/forward arrow it won't go back and forth.
This should not be a hard thing to fix and I think it will just involve passing the title as a parameter in the `Router` link. I will create a PR for this.

#### Carousel renumbering
So the reason why I added a `"block_order"` field in the json was to mimic the models in the database.
Backend told me today though that this will be refactored to the structured you mentioned with the blocks contained into one array and order done by indexing.
I will refactor fe to reflect the change. This will definitely fix all the bugs that are traced back to this renumbering bug.

#### PreviewIcon
Absolutely, I will just put it aside for now.

**Review by petamar — APPROVED** [review]
Just to ask. those two TODO functions in myDocuments are waiting for backend to be able to store documents? Do you have same functions for validating?

**Comment by max-romagnoli** [comment]
> Just to ask. those two TODO functions in myDocuments are waiting for backend to be able to store documents? Do you have same functions for validating?

Yes they are still waiting for backend to be connected. 
And no those functions are just for getting the document data, not the array of mistakes.

**Pull request merged**
