### PR TITLE
Sprint 1: restructure as single django project

### PR DESCRIPTION
**Pull request by nassir90**
The frontend component should exist as an app within the django project. The alternative would be having one server for the API and one server for the UI but that adds unnecessary complexity.

### CODE REVIEW

**Comment by MaxCunningham19** [comment]
So just so I am clear, these changes create the react component as an app which can be used on the Django server? Secondly, is there any chance you have tested to see if this runs/works? If so what commands/process are you using (i.e build the react app, then run the Django app?). 

Also we may wait to ask the client on Tuesday if they would prefer running the application as two separate servers or as one. 

_p.s. this is my first time working with Django so I may ask some stupid questions._

**Comment by nassir90** [comment]
The client and the server are currently independent and have not yet been developed.
They 'work' in that you can run `npm run start` or `python3 manage.py runserver` and get default pages.

In the future, I plan on setting up the front end app according to the video you linked on the discord (https://www.youtube.com/watch?v=JD-age0BPVo) with webpack, babel .etc, at which point I will document building/deployment steps.

I don't think that they will mind us having everything server under Django.

**Comment by MaxCunningham19** [comment]
That sounds good to me.

If I have some free time this evening/ tomorrow morning I can with setting it up according to the video as well. I will work in this branch so who ever gets some free time first can do it.

It would just be good to get it done before people start coding this week.

Good work so far!

**Comment by nassir90** [comment]
I should be able to do it myself don't worry, unless you really want to :laughing:. Also, what state do you want this branch to be in when merged? My initial plan was to just have the restructuring in this branch. Do you also want it to contain a django server capable of serving a React site?

**Comment by nassir90** [comment]
We could also do chained PRs but I feel like that's a bit messy, correct me if I'm wrong and there's a good way to do them. At my old internship I would develop a chain of incremental changes, but the main branch would be being modified at the same time so I would spend a lot of time making sure that my feature chains could be merged with main with no conflicts and it got unwieldly.

**Comment by MaxCunningham19** [comment]
My Opinion is that you should merge this as soon as the file structure is changed - no need to any anything else in. I prefer when merges and changes are as small and as frequent as possible cause as you said otherwise it can get unwieldy and difficult to manage.

**Comment by nassir90** [comment]
I need you to approve the PR tho :smiling_face_with_tear:.

**Review by MaxCunningham19 — APPROVED** [review]
LGTM

**Pull request merged**
