### PR TITLE
Implemented document area with dynamic input

### LINKED ISSUE #18: Sprint 1: Build Document Section
# Build out the Document section.

This entails building a scroll bar for the document, build out the sub sections of the document and the css and styling of the document.

View [RESOURCES](https://github.com/MaxCunningham19/legal_spellcheck/tree/main/resources) for examples.

### PR DESCRIPTION
**Pull request by max-romagnoli**
This PR introduces:
- Carousel and TextBox components
- Carousel : the scrollable area containing input textareas
- TextBox : typeable and auto-resizable input textarea to implement document paragraphs

Minor features:
- Fixed layout to adapt to window size
- Added actual font used in mockup
- Added directory `hooks` for custom hooks

**SEE KNOWN BUGS IN COMMENT BELOW**
When fixed, this PR closes #18

### CODE REVIEW

**Comment by max-romagnoli** [comment]
**KNOWN BUG** @ciannamacmahon 

The paragraphs work for every input size and dynamically resize as needed. _At first render, however, each box loads as **one-line only** text areas._ On type, they resize as intended.
The dynamic resize of the input area is achieved in my code by calling the custom hook `useAutosizeTextArea` that acts on the referenced text area `textAreaRef`. This however does not get called at first render.
I have tried some workarounds, but I am still not very confident with React hooks. The solution might very simple but haven't figured it out.

**Comment by MaxCunningham19** [comment]
My opinion after looking at this would be to merge this branch as it is (or after finishing other small changes). Then create a new item in the product backlog to fix this bug in the future. Better to add the document section in asap and with this bug to then fix later rather then spending too long trying to fix it. 

What is your opinion @ciannamacmahon?

**Review by MaxCunningham19 — APPROVED** [review]
# LGTM
See previous comment w/ regards to bug and how to approach.

**Comment by max-romagnoli** [comment]
Perfect, thank you both for your fb. I'll merge now.

**Pull request merged**
