### PR TITLE
Added some buttons to front end

### PR DESCRIPTION
**Pull request by petamar**
Added some buttons to front end and rsuite extention that is not now used

### CODE REVIEW

**Comment by max-romagnoli** [comment]
Resolving this PR should close #20

**Review by max-romagnoli — APPROVED** [review]
Resolving this PR should close #20

**Review by ciannamacmahon — APPROVED** [review]
The buttons look great. What could be cool to add in going forward, is that the button changes once the user has clicked on it just to show them that the button worked. Eg. when the 'save all' button is clicked, it changes to 'saved' or something to that effect. But great work so far

**Comment by petamar** [comment]
@max-romagnoli looks super great so I merged it. Yeah i dont think we need rsuit. It was pretty much just experiment from my side. @ciannamacmahon created new task for it, will see if there is time for it in this sprint if not we can just move it to next.

**Pull request merged**
