### PR TITLE
Sprint 2: Updated Carousel to dynamically add/remove paragraphs

### LINKED ISSUE #47: Sprint 2: Update Carousel to dynamically add/remove paragraphs
The `Carousel.js` should allow the user to add or remove paragraph text areas.

### PR DESCRIPTION
**Pull request by max-romagnoli**
This PR achieves the following:
* Roll-out of **Icon Buttons**. It is now possible to create `Button.js` components that show svg icons in a flexible way. This is functional to the development of `Navbar.js`.
* **Add paragraphs**. A new type of Button has been added to the end of the Carousel to add an editable textbox area.
* **Remove paragraphs**. Each `TextBox.js` component in Carousel now features a grid layout with the second row being the container for the set of icons to edit/save/validate/remove the individual component.
* **On hover and on focus**. Implemented style and component toggle on hover. This lays foundation for other media features.

Closes #47

### CODE REVIEW

**Review by MaxCunningham19 — APPROVED** [review]
## LGTM 

**NIT**: It might make sense to make two button components. One that is just button and one that is an iconButton to separate out the two and reduce empty html headers.

**Comment by max-romagnoli** [comment]
> ## LGTM
> **NIT**: It might make sense to make two button components. One that is just button and one that is an iconButton to separate out the two and reduce empty html headers.

Sounds good. Either way though we need to take into account an hybrid button that has both test and icons (that is the case for the buttons in navbar). With the current system such buttons would be already implemented.
A solution might be to add a conditional logic, that is:
- If the button gets passed icon and text, then create div for both.
- If the button gets passed only one of the two, then create div for one or the other.
This should be pretty straightforward to implement with a simple check on the props that are being passed in the component.

**Review by petamar — APPROVED** [review]

**Comment by MaxCunningham19** [comment]
> > ## LGTM
> > **NIT**: It might make sense to make two button components. One that is just button and one that is an iconButton to separate out the two and reduce empty html headers.
> 
> Sounds good. Either way though we need to take into account an hybrid button that has both text and icons (that is the case for the buttons in navbar). With the current system such buttons would be already implemented. A solution might be to add a conditional logic, that is:
> 
> * If the button gets passed icon and text, then create div for both.
> * If the button gets passed only one of the two, then create div for one or the other.
> 
> This should be pretty straightforward to implement with a simple check on the props that are being passed in the component.

Sounds good to me

**Comment by max-romagnoli** [comment]
Closing this so we can start working on merging PR #58.
Will not down icon/iconless issue and make a PR later this week to address it.

**Comment by max-romagnoli** [comment]
> > > ## LGTM
> > > **NIT**: It might make sense to make two button components. One that is just button and one that is an iconButton to separate out the two and reduce empty html headers.
> > 
> > 
> > Sounds good. Either way though we need to take into account an hybrid button that has both text and icons (that is the case for the buttons in navbar). With the current system such buttons would be already implemented. A solution might be to add a conditional logic, that is:
> > 
> > * If the button gets passed icon and text, then create div for both.
> > * If the button gets passed only one of the two, then create div for one or the other.
> > 
> > This should be pretty straightforward to implement with a simple check on the props that are being passed in the component.
> 
> Sounds good to me

Fixed this NIT in PR #64. Now spans render only if props are passed in.

**Pull request merged**
